theme: jekyll-theme-cayman
title: Portfolio
description: A website that displays the skills of a developer
url: https://emmanuellekamwa.github.io/
author: kamwa Emmanuelle Alix
plugins:
  - jekyll-seo-tag
  github:
  zip_url: http://github.zip_url/download.zip
  another_url: https://emmanuellekamwa.github.io/
google_analytics: G-ND7F80HZZ1
